Vagrant.configure("2") do |config|
  config.vm.box = "rshash/Ubuntu_20.04-M1-Mac"
  config.vm.provision "shell", inline: <<-SHELL
  sudo apt-get update
  sudo apt-get install -y curl git
  curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
  sudo apt-get install -y nodejs
  sudo apt-get install -y build-essential
  SHELL
end
